### ISSUE TITLE
Panic on `write_or_buf`

### ISSUE THREAD

**Issue by cloudhead** [rust-amplify/io-reactor#22]
Updating to `0.2.0` and running my test suite results in this panic:

```
thread 'z6MknSLrJoTcukLrE435hVNQT4JUhbvWLX4kUzqkEStBU8Vi' panicked at 'WriteAtomic::write_or_buf must handle EGAGAIN, EINTER, EWOULDBLOCK errors by buffering the data', /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/resource.rs:103:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: reactor::resource::WriteAtomic::write_atomic::{{closure}}
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/resource.rs:103:17
   3: core::result::Result<T,E>::map_err
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:861:27
   4: reactor::resource::WriteAtomic::write_atomic
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/resource.rs:102:13
   5: reactor::reactor::Runtime<H,P>::handle_action
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/reactor.rs:661:23
   6: reactor::reactor::Runtime<H,P>::handle_actions
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/reactor.rs:594:31
   7: reactor::reactor::Runtime<H,P>::run
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/reactor.rs:494:13
   8: reactor::reactor::Reactor<C,P>::with::{{closure}}
             at /home/cloudhead/.cargo/registry/src/github.com-1ecc6299db9ec823/io-reactor-0.2.0/src/reactor.rs:292:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'z6MknSLrJoTcukLrE435hVNQT4JUhbvWLX4kUzqkEStBU8Vi' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', radicle-node/src/runtime.rs:260:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1113:23
   4: radicle_node::runtime::Runtime::run
             at /home/cloudhead/src/radicle/heartwood/radicle-node/src/runtime.rs:260:9
   5: radicle_node::test::environment::Node<G>::spawn::{{closure}}
             at /home/cloudhead/src/radicle/heartwood/radicle-node/src/test/environment.rs:316:32
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'test_replication_via_seed' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/cloudhead/src/radicle/heartwood/radicle-node/src/test/environment.rs:139:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1113:23
   4: <radicle_node::test::environment::NodeHandle<G> as core::ops::drop::Drop>::drop
             at /home/cloudhead/src/radicle/heartwood/radicle-node/src/test/environment.rs:137:9
   5: core::ptr::drop_in_place<radicle_node::test::environment::NodeHandle<radicle_crypto::ssh::keystore::MemorySigner>>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ptr/mod.rs:490:1
   6: commands::test_replication_via_seed
             at ./tests/commands.rs:781:1
   7: commands::test_replication_via_seed::{{closure}}
             at ./tests/commands.rs:699:32
   8: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dr-orlovsky** [comment]
Closed with https://github.com/rust-amplify/io-reactor/commit/a430912aac076ac49039536f4b886f323a5973dd

Published v0.2.1 update and yanked buggy v0.2.0
